### ISSUE TITLE
RabbitMQ driver

### ISSUE THREAD

**Issue by santisbon** [fedify-dev/fedify#83]
A RabbitMQ implementation of [MessageQueue](https://jsr.io/@fedify/fedify/doc/federation/~/MessageQueue) just like the one for Redis would be great as a message broker.

Thanks!

**Comment by dahlia** [comment]
This library looks fine: <https://github.com/amqp-node/amqplib>.

**Comment by melroy89** [comment]
[Mbin](https://github.com/MbinOrg/mbin) is indeed also using RabbitMQ. With some technical difficulties sometimes... 

here for info:

![image](https://github.com/dahlia/fedify/assets/628926/5063b6c9-9c74-43a2-b410-85bb224a33d1)

That being said, if you want to implement RabbitMQ. Here are some generic lessons learned from my side of the story: Be sure to set an expire/ TTL as well as a dead-letter.  Be sure to use queue storage version 2 (instead of the old v1). Do not try to retry too often, do not create big queues (the smaller the queues the better, or expect performance issues).

**Comment by ThisIsMissEm** [comment]
You should also be able to fork https://github.com/dahlia/fedify-redis and implement the necessary parts to work with RabbitMQ via the aforementioned ampq driver above.

**Comment by dahlia** [comment]
[Many users want this.](https://hollo.social/@fedify/019265da-a303-74f0-94f8-96d5e2c78f7f)

**Comment by dahlia** [comment]
Created [@fedify/amqp](https://github.com/dahlia/fedify-amqp).

**Comment by dahlia** [comment]
The [benchmark](https://github.com/dahlia/fedify-queue-benchmarks) is also updated.
